#!/usr/bin/env node
// Builds tools/math-quest-qa.html = math-quest.html + tools/qa-agent.js
// appended before </body>. The original game file is never modified.
//
//   node tools/inject-qa.js [--game path/to/math-quest.html] [--out path]
//
// Open the result with ?qa=1 to autostart the agent (overlay on); optional
// &ts=4 (timeScale), &min=30 (maxMinutes), &diff=LITTLE_HERO|ADVENTURER|...
// Without ?qa=1 the page is the normal game; start the agent from the
// DevTools console with startQAAgent({ overlay: true }).
const fs = require('fs');
const path = require('path');

const args = {};
for (let i = 2; i < process.argv.length; i++) {
  const k = process.argv[i];
  if (k.startsWith('--')) { args[k.slice(2)] = process.argv[i + 1]; i++; }
}
const game = path.resolve(args.game || path.join(__dirname, '..', 'math-quest.html'));
const out = path.resolve(args.out || path.join(__dirname, 'math-quest-qa.html'));
const html = fs.readFileSync(game, 'utf8');
const agent = fs.readFileSync(path.join(__dirname, 'qa-agent.js'), 'utf8');
if (/<\/script/i.test(agent)) throw new Error('qa-agent.js must not contain a closing script tag');

const boot = `
(function () {
  var q = new URLSearchParams(location.search);
  if (q.get('qa') !== '1') return;
  window.addEventListener('load', function () {
    startQAAgent({ overlay: true, timeScale: +(q.get('ts') || 1), maxMinutes: +(q.get('min') || 30), difficulty: q.get('diff') || null });
  });
})();`;
const inject = '\n<!-- QA agent (generated by tools/inject-qa.js; not part of the game) -->\n<script>\n' + agent + '\n' + boot + '\n</script>\n';
const at = html.lastIndexOf('</body>');
if (at < 0) throw new Error('no </body> in ' + game);
fs.writeFileSync(out, html.slice(0, at) + inject + html.slice(at));
console.log('wrote ' + out + ' (' + (fs.statSync(out).size / 1e6).toFixed(1) + ' MB); open it with ?qa=1 to autostart the agent');
